<?php

// Are we live?
if (!defined('LIVE')) DEFINE('LIVE', FALSE);

# Constants - site
define('SITE_NAME', 'Exotic Car Club');
define('SITE_URL', 'http://www.exoticcarclub.pl');
define('SITE_EMAIL', 'office@exoticcarclub.pl');

# Constants - $path['call_parts'][...]
define('PATH_SITE', 0);
define('PATH_SUBSITE', 1);

# Constants - folders
define('D_CONFIG', SITE_DIR.'config/');
define('D_TEMPLATES', SITE_DIR.'templates/');
define('D_IMAGES', SITE_DIR.'img/');
define('D_VIEWS', SITE_DIR.'views/');
define('D_FUNCTIONS', SITE_DIR.'functions/');
define('D_INCLUDES', SITE_DIR.'includes/');

#Constants - includes
define('F_MENU', 'menu.php');
define('F_GTM', 'GTM.php');
define('F_URL_PARSE', 'f_url_parse.php');
define('F_FUNCTIONS_DATA', 'f_data.php');
define('F_TRANSLATION', 'f_translation.php');
define('F_HTML_GENERATION', 'f_html_generation.php');

# Constants - files
define('F_HOME', 'home');
define('F_FLEET', 'fleet');
define('F_VEHICLES', 'vehicles');
define('F_VEHICLE', 'vehicle');
define('F_OFFER', 'offer');
define('F_EVENTS', 'events');
define('F_ABOUT', 'about');
define('F_BLOG', 'blog');
define('F_WASZKA', 'waszka');
define('F_PARTNERS', 'partners');
define('F_CONTACT', 'contact');
define('F_FAQ', 'faq');
define('F_404', 'page-unavailable');

#Constants - file dates to reset cached files
define('DT_CSS_UPDATE', '20200101');
define('DT_BOOTSTRAP_JS', '20200101');
define('DT_JS_UPDATE', '20200101');
define('DT_SUPPORT_FUNCTIONS_JS', '20200101');
define('DT_THUMBNAIL_IMG', '20200101');

# Variable
$all_langs = array('pl', 'en');
$GLOBALS['vehicles'] = array(
		array('name' 	=> 	'Lamborghini Aventador SV',
					'slug' 	=> 	'lamborghini-aventador-sv',
					'engine' => '6.5 V12',
					'power' => '750',
					'acceleration' => array(2,8),
					'v-max' => '350',
					'img' 	=>	array('' => '', '-z-uniesionymi-drzwiami' => ' z uniesionymi drzwiami', '-przod' => ' - przód', '-wnetrze' => ' - wnętrze', '-tyl' => ' - tył')),
		array('name' 	=> 	'Lamborghini Aventador',
					'slug' 	=> 	'lamborghini-aventador',
					'cat'		=>	'road',
					'engine' => '6.5L V12',
					'power' => '750',
					'acceleration' => array(2,9),
					'v-max' => '350',
					'img' 	=>	array('' => '', '-i-eurocopter-ec-135p2' => ' i Eurocopter EC 135P2+', '-wnetrze' => ' - wnętrze', '-sylwetka' => ' - sylwetka', '-bok' => ' - bok')),
		array('name' 	=> 	'Lamborghini Urus',
					'slug' 	=> 	'lamborghini-urus',
					'cat'		=>	'road',
					'engine' => '4.0V8',
					'power' => '650',
					'acceleration' => array(3,6),
					'v-max' => '305',
					'img' 	=>	array('' => '', '-zblizenie' => ' - zblizenie', '-tyl' => ' - tył', '-wnetrze' => ' - wnętrze', '-kierownica' => ' - kierownica', '-wykonczenie' => ' - wykończenie')),
		array('name' 	=> 	'Lamborghini Huracan Performante',
					'slug' 	=> 	'lamborghini-huracan-performante',
					'cat'		=>	'road',
					'engine' => '5.2V10',
					'power' => '640',
					'acceleration' => array(2,9),
					'v-max' => '325',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-reflektor-zblizenie' => ' - zbliżenie na przedni reflektor', '-silnik' => ' - silnik', '-tyl' => ' - tył', '-maska' => ' - maska', '-logo-na-masce' => ' - logo na masce', '-deska-rozdzielcza' => ' - deska rozdzielcza', '-kierownica' => ' - kierownica', '-przelaczniki' => ' - przełączniki', '-kolo' => ' - zbliżenie na koło')),
		array('name' 	=> 	'McLaren 720s',
					'slug' 	=> 	'mclaren-720s',
					'cat'		=>	'road',
					'engine' => '4.0V8 biturbo',
					'power' => '720',
					'acceleration' => array(2,9),
					'v-max' => '341',
					'img' 	=>	array('' => '', '-podnoszone-drzwi' => ' - podnoszone drzwi', '-tyl' => ' - tył', '-tyl-zblizenie' => ' - zbliżenie na tył', '-wnetrze' => ' - wnętrze')),
		array('name' 	=> 	'Aston Martin Vanquish',
					'slug' 	=> 	'aston-martin-vanquish',
					'cat'		=>	'road',
					'engine' => '6.0 V12',
					'power' => '570',
					'acceleration' => array(3,8),
					'v-max' => '324',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-wnetrze' => ' - wnętrze', '-kierownica' => ' - kierownica')),
		array('name' 	=> 	'Ferrari Portofino',
					'slug' 	=> 	'ferrari-portofino',
					'cat'		=>	'road',
					'engine' => '3.9 V8',
					'power' => '600',
					'acceleration' => array(3,5),
					'v-max' => '320',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-wnetrze' => ' - wnętrze', '-logo' => ' - zbliżenie na logo na boku')),
		array('name' 	=> 	'Maserati GranCabrio MC',
					'slug' 	=> 	'maserati-grancabrio-mc',
					'cat'		=>	'road',
					'engine' => '4.7 V8',
					'power' => '460',
					'acceleration' => array(4,9),
					'v-max' => '289',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-sylwetka' => ' - sylwetka', '-reflektor' => ' - zbliżenie na przedni reflektor', '-wnetrze' => ' - wnętrze', '-wnetrze-2' => ' - wnętrze')),
		array('name' 	=> 	'Ferrari 488 GTB',
					'slug' 	=> 	'ferrari-488-gtb',
					'cat'		=>	'road',
					'engine' => '3.9 V8 Turbo',
					'power' => '670',
					'acceleration' => array(3,0),
					'v-max' => '330',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-wnetrze' => ' - wnętrze', '-zegary' => ' - zegary')),
		array('name' 	=> 	'Ferrari 458 Italia',
					'slug' 	=> 	'ferrari-458-italia',
					'cat'		=>	'road',
					'engine' => '4.5 V8',
					'power' => '570',
					'acceleration' => array(3,4),
					'v-max' => '325',
					'img' 	=>	array('' => '', '-bok' => ' - bok', '-tyl' => ' - tył', '-wnetrze' => ' - wnętrze', '-kierownica' => ' - kierownica')),
		array('name' 	=> 	'Chevrolet Corvette ZR1',
					'slug' 	=> 	'chevrolet-corvette-zr1',
					'cat'		=>	'road',
					'engine' => '6.2 LT5 V8',
					'power' => '755',
					'acceleration' => array(3,1),
					'v-max' => '338',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-bok' => ' - bok', '-wnetrze' => ' - wnętrze')),
		array('name' 	=> 	'Chevrolet Camaro ZL1',
					'slug' 	=> 	'chevrolet-camaro-zl1',
					'cat'		=>	'road',
					'engine' => '6.2 LT4 V8 kompresor',
					'power' => '640',
					'acceleration' => array(3,5),
					'v-max' => '300',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-sylwetka' => ' - sylwetka', '-tyl' => ' - tył', '-bok' => ' - zbliżenie na bok', '-wnetrze' => ' - wnętrze')),
		array('name' 	=> 	'Porsche 911 Turbo S Cabrio',
					'slug' 	=> 	'porsche-911-turbo-s-cabrio',
					'cat'		=>	'road',
					'engine' => '3.8 B6',
					'power' => '580',
					'acceleration' => array(3,0),
					'v-max' => '330',
					'img' 	=>	array('' => '', '-z-otwartym-dachem' => ' - z otwartym dachem', '-wnetrze' => ' - wnętrze', '-wnetrze-przod' => ' - wnętrze - przód')),
		array('name' 	=> 	'Porsche 911 Turbo S',
					'slug' 	=> 	'porsche-911-turbo-s',
					'cat'		=>	'road',
					'engine' => '3.8 B6',
					'power' => '580',
					'acceleration' => array(2,9),
					'v-max' => '330',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-sylwetka' => ' - sylwetka', '-tyl' => ' - tył', '-bok' => ' - zbliżenie na bok', '-wnetrze' => ' - wnętrze')),
		array('name' 	=> 	'Porsche 911 4S Cabrio',
					'slug' 	=> 	'porsche-911-4s-cabrio',
					'cat'		=>	'road',
					'engine' => '3.0 boxer6',
					'power' => '420',
					'acceleration' => array(4,5),
					'v-max' => '306',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-tyl-2' => ' - tył', '-tyl-zblizenie' => ' - zbliżenie na tył', '-reflektor' => ' - zbliżenie na przedni reflektor', '-wnetrze' => ' - wnętrze', '-kierownica' => ' - kierownica')),
		array('name' 	=> 	'Porsche 911 Targa 4S',
					'slug' 	=> 	'porsche-911-targa-4s',
					'cat'		=>	'road',
					'engine' => '3.0 B6',
					'power' => '420',
					'acceleration' => array(4,4),
					'v-max' => '303',
					'img' 	=>	array('' => '', '-bok' => ' - bok', '-sylwetka' => ' - sylwetka')),
		array('name' 	=> 	'Porsche Panamera Turbo 2016',
					'slug' 	=> 	'porsche-panamera-turbo-2016',
					'cat'		=>	'road',
					'engine' => 'V8',
					'power' => '550',
					'acceleration' => array(3,8),
					'v-max' => '306',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-bok' => ' - bok', '-wnetrze-przod' => ' - wnętrze - przód', '-wnetrze-tyl' => ' - wnętrze - tył')),
		array('name' 	=> 	'Porsche Panamera Diesel',
					'slug' 	=> 	'porsche-panamera-diesel',
					'cat'		=>	'road',
					'engine' => 'V8',
					'power' => '422',
					'acceleration' => array(4,5),
					'v-max' => '285',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-wnetrze-przod' => ' - wnętrze - przód', '-wnetrze-tyl' => ' - wnętrze - tył')),
		array('name' 	=> 	'Nissan GT-R Nismo',
					'slug' 	=> 	'nissan-gt-r-nismo',
					'cat'		=>	'road',
					'engine' => '3.8 V6 TURBO',
					'power' => '600',
					'acceleration' => array(2,7),
					'v-max' => '310',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-sylwetka' => ' - sylwetka', '-tyl' => ' - tył', '-bok' => ' - bok', '-wnetrze' => ' - wnętrze')),
		array('name' 	=> 	'BMW i8',
					'slug' 	=> 	'bmw-i8',
					'cat'		=>	'road',
					'engine' => '1.5 R3',
					'power' => '362',
					'acceleration' => array(4,4),
					'v-max' => '250',
					'img' 	=>	array('' => '', '-z-uniesionymi-drzwiami' => ' z uniesionymi drzwiami', '-bok' => ' - bok', '-bok-zblizenie' => ' - zbliżenie na bok', '-reflektor' => ' - zbliżenie na przedni reflektor', '-wnetrze' => ' - wnętrze')),
		array('name' 	=> 	'Mercedes AMG S63 Cabrio',
					'slug' 	=> 	'mercedes-amg-s63-cabrio',
					'cat'		=>	'road',
					'engine' => '5.5',
					'power' => '670',
					'acceleration' => array(3,7),
					'v-max' => '320',
					'img' 	=>	array('' => '', '-z-otwartym-dachem' => ' - z otwartym dachem', '-bok' => ' - bok', '-wnetrze-przod' => ' - wnętrze - przód', '-wnetrze-tyl' => ' - wnętrze - tył')),
		array('name' 	=> 	'Mercedes E63 AMG S',
					'slug' 	=> 	'mercedes-e63-amg-s',
					'cat'		=>	'road',
					'engine' => '4.0 V8 Biturbo',
					'power' => '612',
					'acceleration' => array(3,4),
					'v-max' => '250',
					'img' 	=>	array('' => '', '-sylwetka' => ' - sylwetka', '-bok' => ' - bok', '-tyl' => ' - tył', '-wnetrze-przod' => ' - wnętrze - przód', '-wnetrze-tyl' => ' - wnętrze - tył')),
		array('name' 	=> 	'Mercedes S400d',
					'slug' 	=> 	'mercedes-s400d',
					'cat'		=>	'road',
					'engine' => '3.0 R6',
					'power' => '340',
					'acceleration' => array(5,4),
					'v-max' => '250',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-reflektor-przedni' => ' - zbliżenie na przedni reflektor', '-reflektor-tylny' => ' - zbliżenie na tylny reflektor', '-wnetrze-przod' => ' - wnętrze - przód', '-wnetrze-tyl' => ' - wnętrze - tył')),
		array('name' 	=> 	'Maserati Quattroporte S Q4',
					'slug' 	=> 	'maserati-quattroporte-s-q4',
					'cat'		=>	'road',
					'engine' => '3.0 V6',
					'power' => '410',
					'acceleration' => array(4,9),
					'v-max' => '283',
					'img' 	=>	array('' => '', '-bok' => ' - bok', '-tyl' => ' - tył', '-wnetrze' => ' - wnętrze', '-w-trasie' => ' w trasie')),
		array('name' 	=> 	'Mercedes G500 AMG',
					'slug' 	=> 	'mercedes-g500-amg',
					'cat'		=>	'road',
					'engine' => '4.0 V8',
					'power' => '422',
					'acceleration' => array(5,9),
					'v-max' => '210',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-bok' => ' - bok', '-reflektor' => ' - zbliżenie na przedni reflektor', '-szyberdach' => ' - szyberdach', '-wnetrze' => ' - wnętrze')),
		array('name' 	=> 	'Maserati Levante',
					'slug' 	=> 	'maserati-levante',
					'cat'		=>	'road',
					'engine' => '3.0 V6',
					'power' => '470',
					'acceleration' => array(5,2),
					'v-max' => '264',
					'img' 	=>	array('' => '', '-lewy-bok' => ' - lewy bok', '-prawy-bok' => ' - prawy bok', '-przod' => ' - przód')),
		array('name' 	=> 	'BMW 740d xDrive',
					'slug' 	=> 	'bmw-740d-xdrive',
					'cat'		=>	'road',
					'engine' => '3.0 R6',
					'power' => '320',
					'acceleration' => array(5,3),
					'v-max' => '250',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-wnetrze' => ' - wnętrze', '-kierownica' => ' - kierownica')),
		array('name' 	=> 	'Mercedes V Class',
					'slug' 	=> 	'mercedes-v-class',
					'cat'		=>	'road',
					'engine' => '2.2 R4',
					'power' => '190',
					'acceleration' => array(9,1),
					'v-max' => '206',
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-wnetrze' => ' - wnętrze', '-siedzenia' => ' - siedzenia'))
		/*, array('name' 	=> 	'Ford Fiesta Proto',
					'slug' 	=> 	'ford-fiesta-proto',
					'cat'		=>	'road',
					'engine' => '2.0 R4 Turbo',
					'power' => '600',
					'acceleration' => array(3,4),
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-tyl' => ' - tył', '-wnetrze' => ' - wnętrze')),
		array('name' 	=> 	'Cranchi Sixty Fly',
					'slug' 	=> 	'cranchi-sixty-fly',
					'cat'		=>	'water',
					'length' => 18.52,
					'width' => 4.85,
					'power' => '2x 625',
					'tank'	=> 2000,
					'img' 	=>	array('' => '', '-przod' => ' - przód', '-stolik-nawigacyjny' => ' - stolik nawigacyjny', '-messa' => ' - messa', '-kabina' => ' - kabina')),
		array('name' 	=> 	'Helikopter Robinson 44',
					'slug' 	=> 	'helikopter-robinson-44',
					'cat'		=>	'air',
					'engine' => 'Lycoming IO-540-AE1A5 6-cylindrowy',
					'range' => '560',
					'power' => '260',
					'v-max' => '240',
					'img' 	=>	array('' => '')),
		array('name' 	=> 	'Eurocopter EC 135P2+',
					'slug' 	=> 	'eurocopter-ec-135p2',
					'cat'		=>	'air',
					'engine' => 'PW206B2',
					'range' => '620',
					'power' => '816 shp / 609 kW',
					'v-max' => '254',
					'img' 	=>	array('' => '', '-2' => '', '-bok' => ' - bok', '-bok-zblizenie' => ' - zbliżenie na bok', '-tyl' => ' - tył'))*/
);

# Path language matrix
$GLOBALS['path_lang_matrix'] = array(
	'pl' => array(	'' => F_HOME,
					'flota' => F_FLEET,
					'samochody' => F_VEHICLES,
					'samochod' => F_VEHICLE,
					'oferta' => F_OFFER,
					'eventy' => F_EVENTS,
					'o-nas' => F_ABOUT,
					'blog' => F_BLOG,
					'historia-przemek-waszczuk' => F_WASZKA,
					'kontakt' => F_CONTACT,
					'partnerzy' => F_PARTNERS,
					'najczestsze-pytania' => F_FAQ,
					'strona-nie-istnieje' => F_404),
	'en' => array(	'en' => F_HOME,
					'fleet' => F_FLEET,
					'cars' => F_VEHICLES,
					'car' => F_VEHICLE,
					'offer' => F_OFFER,
					'events' => F_EVENTS,
					'about-us' => F_ABOUT,
					'blog' => F_BLOG,
					'history-przemek-waszczuk' => F_WASZKA,
					'contact' => F_CONTACT,
					'partners' => F_PARTNERS,
					'faq' => F_FAQ,
					'page-unavailable' => F_404)
);
$GLOBALS['path_lang_translate'] = array(
	'pl' => array(	F_HOME => '',
					F_FLEET => 'flota',
					F_VEHICLES => 'samochody',
					F_VEHICLE => 'samochod',
					F_OFFER => 'oferta',
					F_EVENTS => 'eventy',
					F_ABOUT => 'o-nas',
					F_BLOG => 'blog',
					F_WASZKA => 'historia-przemek-waszczuk',
					F_CONTACT => 'kontakt',
					F_PARTNERS => 'partnerzy',
					F_FAQ => 'najczestsze-pytania',
					F_404 => 'strona-nie-istnieje'),
	'en' => array(	F_HOME => 'en',
					F_FLEET => 'fleet',
					F_VEHICLES => 'cars',
					F_VEHICLE => 'car',
					F_OFFER => 'offer',
					F_EVENTS => 'events',
					F_ABOUT => 'about-us',
					F_BLOG => 'blog',
					F_WASZKA => 'history-przemek-waszczuk',
					F_CONTACT => 'contact',
					F_PARTNERS => 'partners',
					F_FAQ => 'faq',
					F_404 => 'page-unavailable')
);
